In [2]:
import numpy as np

list_data=[1,2,3,4,5]
arr=np.array(list_data)
print("一维数组：",arr)
print("数组类型：",type(arr))

list_2d=[[1,2,3],[4,5,6]]
arr_2d=np.array(list_2d)
print("\n二维数组：")
print(arr_2d)
print("二维数组类型：",type(arr_2d))

一维数组： [1 2 3 4 5]
数组类型： <class 'numpy.ndarray'>

二维数组：
[[1 2 3]
 [4 5 6]]
二维数组类型： <class 'numpy.ndarray'>


In [3]:

print("\n数组属性：")
print("维度：",arr_2d.ndim)
print("形状：",arr_2d.shape)
print("元素总数：",arr_2d.size)
print("数据类型：",arr_2d.dtype)


数组属性：
维度： 2
形状： (2, 3)
元素总数： 6
数据类型： int64


In [4]:
print("\n向量化运算：")
print("数组+2",arr_2d+2)
print("数组*3",arr_2d*3)


向量化运算：
数组+2 [[3 4 5]
 [6 7 8]]
数组*3 [[ 3  6  9]
 [12 15 18]]


In [5]:
import time

py_list=list(range(10000000))
start=time.time()
result=[x+2 for x in py_list]
py_time=time.time()-start

np_arr=np.array(py_list)
start=time.time()
result=np_arr+2
np_time=time.time()-start

print(f"\n性能对比：")
print(f"Python列表时间：{py_time:.4f}秒")
print(f"NumPy数组时间：{np_time:.4f}秒")
print(f"NumPy数组速度提升：{py_time/np_time:.2f}倍")


性能对比：
Python列表时间：2.9137秒
NumPy数组时间：0.6366秒
NumPy数组速度提升：4.58倍


In [6]:
list_data=[1,2,3,4,5]
arr_from_list=np.array(list_data)
print("从列表创建：",arr_from_list)

tuple_data=(6,7,8,9,10)
arr_from_tuple=np.array(tuple_data)
print("从元组创建：",arr_from_tuple)

nested_list=[[1,2,3],[4,5,6],[7,8,9]]
arr_2d=np.array(nested_list)
print("二维数组：",arr_2d)

从列表创建： [1 2 3 4 5]
从元组创建： [ 6  7  8  9 10]
二维数组： [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
zeros_arr=np.zeros((3,4))
print("3x4全零数组：",zeros_arr)

ones_arr=np.ones((2,3))
print("2x3全1数组：", ones_arr)

identity=np.eye(4)
print("4x4单位矩阵：",identity)

empty_arr=np.empty((2,2))
print("2x2未初始化数组：",empty_arr)

full_arr=np.full((2,3),7)
print("2x3全7数组：",full_arr)

3x4全零数组： [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2x3全1数组： [[1. 1. 1.]
 [1. 1. 1.]]
4x4单位矩阵： [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2x2未初始化数组： [[1. 1.]
 [1. 1.]]
2x3全7数组： [[7 7 7]
 [7 7 7]]


In [8]:
ranger_arr=np.arange(0,10,2)
print("0到10步长为2的数组：",ranger_arr)

lin_arr=np.linspace(0,10,5)
print("0到10等间隔5个数的数组：",lin_arr)

log_arr=np.logspace(0,2,5)
print("10^0到10^2等间隔5个数的数组：",log_arr)

0到10步长为2的数组： [0 2 4 6 8]
0到10等间隔5个数的数组： [ 0.   2.5  5.   7.5 10. ]
10^0到10^2等间隔5个数的数组： [  1.           3.16227766  10.          31.6227766  100.        ]


In [9]:
np.random.seed(42)

rand_arr=np.random.rand(3,3)
print("3x3随机数组：",rand_arr)

randn_arr=np.random.randn(3,3)
print("3x3标准正态分布随机数组：",randn_arr)

randint_arr=np.random.randint(0,100,(3,4))
print("3x4随机整数数组：",randint_arr)

3x3随机数组： [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
3x3标准正态分布随机数组： [[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]
3x4随机整数数组： [[79 14 61 61]
 [46 61 50 54]
 [63  2 50  6]]


In [10]:
original=np.array([[1,2],[3,4]])
copy_arr=np.copy(original)
print("原始数组：",original)
print("复制数组：",copy_arr)
print("它们是同一个对象吗？",original is copy_arr)
print("它们的值相等吗？",np.array_equal(original,copy_arr))

zeros_like=np.zeros_like(original)
print("与原数组形状相同的全零数组：",zeros_like)

原始数组： [[1 2]
 [3 4]]
复制数组： [[1 2]
 [3 4]]
它们是同一个对象吗？ False
它们的值相等吗？ True
与原数组形状相同的全零数组： [[0 0]
 [0 0]]


In [11]:
x=np.array([0,1,2])
y=np.array([0,1,2,3])
X,Y=np.meshgrid(x,y)
print("X坐标矩阵：\n",X)
print("Y坐标矩阵：\n",Y)

X坐标矩阵：
 [[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
Y坐标矩阵：
 [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]


In [12]:
diag_arr=np.diag([1,2,3,4])
print("对角线数组：\n",diag_arr)

vander_arr=np.vander([1,2,3],3)
print("范德蒙德矩阵：\n",vander_arr)

对角线数组：
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
范德蒙德矩阵：
 [[1 1 1]
 [4 2 1]
 [9 3 1]]


In [13]:
float_arr=np.array([1,2,3],dtype=np.float32)
print("float32数组：",float_arr,"数据类型：",float_arr.dtype)

int_arr=np.array([1.1,2.2,3.3],dtype=np.int32)
print("int32数组：",int_arr,"数据类型：",int_arr.dtype)

complex_arr=np.array([1,2,3],dtype=np.complex128)
print("complex128数组：",complex_arr,"数据类型：",complex_arr.dtype)

bool_arr=np.array([0,1,0,1],dtype=np.bool_)
print("bool数组：",bool_arr,"数据类型：",bool_arr.dtype)

float32数组： [1. 2. 3.] 数据类型： float32
int32数组： [1 2 3] 数据类型： int32
complex128数组： [1.+0.j 2.+0.j 3.+0.j] 数据类型： complex128
bool数组： [False  True False  True] 数据类型： bool


In [14]:
magic_square=np.array([[8,1,6],[3,5,7],[4,9,2]])
print("3x3魔方矩阵：\n",magic_square)

x = np.linspace(0, 2*np.pi, 20)  # 0到2π，20个点
y = np.sin(x)
print("正弦波x坐标:", x)
print("正弦波y坐标:", y)

3x3魔方矩阵：
 [[8 1 6]
 [3 5 7]
 [4 9 2]]
正弦波x坐标: [0.         0.33069396 0.66138793 0.99208189 1.32277585 1.65346982
 1.98416378 2.31485774 2.64555171 2.97624567 3.30693964 3.6376336
 3.96832756 4.29902153 4.62971549 4.96040945 5.29110342 5.62179738
 5.95249134 6.28318531]
正弦波y坐标: [ 0.00000000e+00  3.24699469e-01  6.14212713e-01  8.37166478e-01
  9.69400266e-01  9.96584493e-01  9.15773327e-01  7.35723911e-01
  4.75947393e-01  1.64594590e-01 -1.64594590e-01 -4.75947393e-01
 -7.35723911e-01 -9.15773327e-01 -9.96584493e-01 -9.69400266e-01
 -8.37166478e-01 -6.14212713e-01 -3.24699469e-01 -2.44929360e-16]


In [16]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("原始数组：\n",arr)

print("数据维度（ndim）：",arr.ndim)
print("数据形状（shape）：",arr.shape)
print("数据元素总数（size）：",arr.size)
print("数据类型（dtype）：",arr.dtype)
print("每个元素字节大小（itemsize）：",arr.itemsize,"字节")
print("数据字节总数（nbytes）：",arr.nbytes,"字节")
print("数组的转置（T）：\n",arr.T)

原始数组：
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
数据维度（ndim）： 2
数据形状（shape）： (4, 3)
数据元素总数（size）： 12
数据类型（dtype）： int64
每个元素字节大小（itemsize）： 8 字节
数据字节总数（nbytes）： 96 字节
数组的转置（T）：
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [18]:
print("\n=== 4. 整数数组索引（花式索引） ===")
arr = np.array([10, 20, 30, 40, 50])
print("原始数组:", arr)

# 使用整数列表索引
indices = [0, 2, 4]
print("arr[[0, 2, 4]]:", arr[[0, 2, 4]])  # 获取第0、2、4个元素
print("arr[[4, 2, 0]]:", arr[[4, 2, 0]])  # 可以改变顺序
print("arr[[0, 0, 1, 1, 2]]:", arr[[0, 0, 1, 1, 2]])  # 可以重复索引


=== 4. 整数数组索引（花式索引） ===
原始数组: [10 20 30 40 50]
arr[[0, 2, 4]]: [10 30 50]
arr[[4, 2, 0]]: [50 30 10]
arr[[0, 0, 1, 1, 2]]: [10 10 20 20 30]


In [19]:
print("\n=== 4. 调整维度 ===")
# 增加维度：使用np.newaxis或reshape
arr = np.array([1, 2, 3])
print("原始一维数组:", arr, "形状:", arr.shape)

# 增加一个轴，变为行向量（1行3列）
arr_row = arr[np.newaxis, :]
print("增加行维度（np.newaxis, :）:", arr_row, "形状:", arr_row.shape)

# 增加一个轴，变为列向量（3行1列）
arr_col = arr[:, np.newaxis]
print("增加列维度（:, np.newaxis）:\n", arr_col, "形状:", arr_col.shape)



=== 4. 调整维度 ===
原始一维数组: [1 2 3] 形状: (3,)
增加行维度（np.newaxis, :）: [[1 2 3]] 形状: (1, 3)
增加列维度（:, np.newaxis）:
 [[1]
 [2]
 [3]] 形状: (3, 1)


In [22]:
print("=== 1. 连接（concatenate） ===")
# 一维数组连接
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# 沿现有轴（默认轴0）连接
result = np.concatenate((a, b, c),axis=0)
print("一维数组连接:", result)

=== 1. 连接（concatenate） ===
一维数组连接: [1 2 3 4 5 6 7 8 9]


In [23]:
print("\n=== 2. 堆叠（stack） ===")
# 堆叠会增加新的维度
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# 沿新轴堆叠（默认轴0，增加第一个维度）
stack_0 = np.stack((a, b, c), axis=0)
print("沿轴0堆叠（默认）:\n", stack_0, "形状:", stack_0.shape)


=== 2. 堆叠（stack） ===
沿轴0堆叠（默认）:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 形状: (3, 3)
